### ISSUE TITLE
"a string bvalue".to_s?  no method error

### ISSUE THREAD

**Issue by MadBomber** [manveru/ffi-tk#6]
I just saw the update and thought I'd take a look.  The hello_world example in the README worked in `irb` so next thing I did was go to the examples directory within the gem install directory and execute the first example `ruby choose_color.rb`  Wham! got the error after having picked a color....

```
undefined method `to_s?' for "#1abc96":String
Did you mean?  to_s
               to_sym
               to_str
               to_r
               to_f
               to_i
               to_c
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/command/choose_color.rb:28:in `choose_color'
choose_color.rb:10:in `block in <main>'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/event/handler.rb:15:in `invoke'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/event/data.rb:58:in `call'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:132:in `block (2 levels) in tcl_event'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:131:in `catch'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:131:in `block in tcl_event'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:130:in `catch'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:130:in `tcl_event'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/ffi/tcl.rb:92:in `call'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/ffi/tcl.rb:92:in `Tcl_DoOneEvent'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/ffi/tcl.rb:92:in `do_one_event'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/ffi/tcl/interp.rb:63:in `do_one_event'
/Users/dewayne/.rvm/gems/ruby-2.5.0/gems/ffi-tk-2018.02.20/lib/ffi-tk/tk.rb:56:in `mainloop'
choose_color.rb:23:in `<main>'
    while executing
"::RubyFFI::event 0 "<Key>" 11 ?? ?? ?? ?? ?? 0x7fd403ab1c90 32 ?? ?? ?? 0 -885731115 ?? -5 -74 \  ?? ?? 0 space 32 ?? 0xa 0x0 2 . 0 0 "
    (command bound to event)
```

**Comment by manveru** [comment]
Thanks for the report, the PR should fix it.
